ansible/provisoning/deploy-portainer.yaml
container_name is not supportet by ansible module community.docker.docker_volume anymore. Changed to name
=> container_name -> name

docker-compose/prometheus/exporters/Nvidia DGCM exporter/README.md, docker-compose/prometheus/exporters/Nvidia DGCM exporter/docker-compose.yml, docker-compose/prometheus/exporters/Nvidia_smi_exporter/README.md, docker-compose/prometheus/exporters/Nvidia_smi_exporter/docker-compose.yml
First real PR.
I'm not a coder , just learned docker on the fly.
This compose or better yet , addition to a Prometheus (stack/compose file) is my way of monitoring my GPU on my server.
I hope it helps somebody
=> Adding DCGM and Nvidia-SMI to list of exporters

docker-compose/portainer/docker-compose.yml
=> portainer-data volume declaration is missing in compose file

.github/pull_request_template.md, CONTRIBUTING.md
Created a contributing guide to help potential contributors contribute to the project.
=> Add CONTRIBUTING.md

docker-compose/heimdall/heimdall.yaml
I have added a simple heimdall docker-compose boilerplate. A useful dashboard for your docker containers.
=> Added heimdall.yaml to the boilerplates - a docker-compose file

github-actions/kubectl/kubernetes-deploy.yml, github-actions/scp-action/copy-config-files.yml, github-actions/ssh-action/restart-docker.yml
=> Add GitHub Actions to boilerplates

docker-compose/passbolt/docker-compose.yml
=> Fix: typo with commands to start passbolt-app at the related docker-compose

CONTRIBUTING.md, README.md, kubernetes/certmanager/README.md, kubernetes/portainer/README.md, kubernetes/traefik/README.md, packer/proxmox/README.md, terraform/proxmox/README.md
Here is a list of rules that have been applied:
- [MD009](https://github.com/DavidAnson/markdownlint/blob/main/doc/md009.md) - Trailing spaces
- [MD022](https://github.com/DavidAnson/markdownlint/blob/main/doc/md022.md) - Headings should be surrounded by blank lines
- [MD025](https://github.com/DavidAnson/markdownlint/blob/main/doc/md025.md) - Multiple top-level headings in the same document
- [MD026](https://github.com/DavidAnson/markdownlint/blob/main/doc/md026.md) - Trailing punctuation in heading
- [MD029](https://github.com/DavidAnson/markdownlint/blob/main/doc/md029.md) - Ordered list item prefix
- [MD031](https://github.com/DavidAnson/markdownlint/blob/main/doc/md031.md) - Fenced code blocks should be surrounded by blank lines
- …
=> Following `markdownlint` rules to enforce standards and consistency

docker-compose/homeassistant/docker-compose.yaml
=> home assistant update

docker-compose/teleport/docker-compose.yaml
=> updated docker compose file

docker-compose/twingate/connector/docker-compose.yaml
=> twingate compose file

ansible/installation/inst-k8s/README.md, ansible/installation/inst-k8s/ansible.cfg, ansible/installation/inst-k8s/inst-k8s.yaml, ansible/installation/inst-k8s/k8s_worker_node_connection.j2
=> Install K8s

ansible/installation/int-qemu-agent.yaml, ansible/update/upd-apt.yaml
Added a ansible scripts to install qemu-agent and a script to update linux based on package manager apt or yum
Checklist:
- [x ] My pull request has a descriptive title. (unlike `Update index.md`). Check [this](https://www.conventionalcommits.org/en/v1.0.0/) guide regarding titles.
- [x ] If applicable, I have tested these changes.
Closes #XXXXX
Thank you for allowing me to be part of this project, i am looking forward to add more scripts.
=> 2 new ansible scripts

docker-compose/cadvisor/docker-compose.yaml
=> remove network mode

docker-compose/influxdb/docker-compose.yaml
=> update influxdb compose

docker-compose/influxdb/docker-compose.yaml, docker-compose/mariadb/docker-compose.yaml
=> updated mariadb compose

kubernetes/traefik/values.yml
=> Traefik latest helm chart changes to ports.web.redirectTo

packer/proxmox/ubuntu-server-jammy/ubuntu-server-jammy.pkr.hcl
Updated source to proxmox-iso
- I have tested these changes on Proxmox OS v7-4
=> Update proxmox-iso for ubuntu-server-jammy.pkr.hcl source

docker-compose/ansiblesemaphore/docker-compose.yaml
=> chore: upgrade Ansible Semaphore 2.8.90 -> 2.9.45

docker-compose/traefik/docker-compose.yaml
=> chore: upgrade Traefik 2.10.5 -> 2.11.0

docker-compose/influxdb/docker-compose.yaml
=> chore: upgrade InfluxDB 2.7.1 -> 2.7.5

docker-compose/homer/docker-compose.yaml
=> chore: upgrade Homer 23.05.1 -> 23.10.1

CONTRIBUTING.md
=> fix: update URLs in contributing document

docker-compose/pihole/docker-compose.yaml
While at it, also sort list of volumes in lexical order and at the missing YAML document marker.
Checklist:
=> fix: add missing Pihole volume definition

docker-compose/prometheus/docker-compose.yaml
=> chore: upgrade Prometheus 2.50.0 -> 2.50.1

docker-compose/heimdall/docker-compose.yaml
=> chore: upgrade Heimdall 2.5.6 -> 2.6.1

docker-compose/duplicati/docker-compose.yaml
As this is based on a `linuxserver.io` [1] container image it makes sense to use their `lscr.io` registry gateway service instead.
[1] https://www.linuxserver.io/
Checklist:
=> chore: pin version of Duplicati to 2.0.7

.github/issue_template.md, .github/pull_request_template.md
*Please write all text in English in order to facilitate communication and collaboration, and follow this checklist. It will help the contributors to review your PR. Thank you!*
*If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.*
Closes #157
---
=> added templates for issues and prs

docker-compose/nodeexporter/docker-compose.yaml
*Please write all text in English in order to facilitate communication and collaboration, and follow this checklist. It will help the contributors to review your PR. Thank you!*
*If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.*
---
=> chore: upgrade Node Exporter 1.5.0 -> 1.7.0

docker-compose/nginxproxymanager/docker-compose.yaml
*Please write all text in English in order to facilitate communication and collaboration, and follow this checklist. It will help the contributors to review your PR. Thank you!*
---
=> chore: upgrade Nginx Proxy Manager 2.10.3 -> 2.11.1

docker-compose/homeassistant/docker-compose.yaml
*Please write all text in English in order to facilitate communication and collaboration, and follow this checklist. It will help the contributors to review your PR. Thank you!*
*If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.*
---
=> chore: upgrade Home Assistant 2024.3.0 -> 2024.3.1

docker-compose/ansiblesemaphore/docker-compose.yaml, docker-compose/authentik/docker-compose.yaml, docker-compose/bind9/docker-compose.yaml, docker-compose/homer/docker-compose.yaml, docker-compose/influxdb/docker-compose.yaml, docker-compose/mariadb/docker-compose.yaml, docker-compose/nginxproxymanager/docker-compose.yaml, docker-compose/nvidiasmi/docker-compose.yaml, docker-compose/passbolt/docker-compose.yaml, docker-compose/pihole/docker-compose.yaml, docker-compose/portainer-agent/docker-compose.yaml, docker-compose/portainer/docker-compose.yaml, docker-compose/postgres/docker-compose.yaml, docker-compose/prometheus/docker-compose.yaml, docker-compose/swag/docker-compose.yaml, docker-compose/traefik/docker-compose.yaml, docker-compose/uptimekuma/docker-compose.yaml
Consistently always reference the full container image name including its registry.
---
=> feat: always reference the full image name incl. the registry

kestra/docker/file-build.yaml, kestra/docker/git-build.yaml, kestra/inputs.yaml, kestra/python/command.yaml, kestra/python/script.yaml, kestra/variables.yaml, kestra/webhook.yaml
=> Kestra_boilerplates_init

kestra/docker/file-build.yaml, kestra/docker/git-build.yaml, kestra/inputs.yaml, kestra/python/command.yaml, kestra/python/script.yaml, kestra/variables.yaml, kestra/webhook.yaml
Fix various issues in Kestra reported by yamllint.
---
=> Fix various issues in Kestra reported by yamllint

docker-compose/nextcloud/docker-compose.yaml
Provide a supported version of MariaDB to Nextcloud.
---
=> chore(deps): align version of MariaDB with Nextcloud 29

renovate.json
Enable `separateMinorPatch` flag in Renovate
---
=> fix: enable `separateMinorPatch` flag in Renovate

renovate.json
Fix Renovate regular expression as image tags are never empty
---
=> fix: fix Renovate regular expression as image tags are never empty

docker-compose/homepage/docker-compose.yaml
Fix double-colon typo in the Homepage image spec.
---
=> fix: fix double-colon typo in the Homepage image spec

renovate.json
Remove superfluous comma after the last element of the list.
---
=> fix: fix typo

docker-compose/passbolt/docker-compose.yaml
Don't use `latest` tag for the Passbolt container image.
---
=> chore(deps): don't use `latest` tag for Passbolt

docker-compose/swag/docker-compose.yaml
Add image tags to Docker Compose of Swag.
---
=> chore(deps): add image tags to Docker Compose of Swag

docker-compose/factory/runner-pool/docker-compose.yaml
Fully qualify image name of `docker.io/refactr/runner-pool`.
---
=> Fully qualify image name of `docker.io/refactr/runner-pool`

docker-compose/pihole/docker-compose.yaml
Use versioned image tags for Pi-hole.
---
=> chore(deps): use versioned image tags for Pi-hole

docker-compose/traefik/config/traefik.yaml
Hide the nagging Upgrade button on Traefik's dashboard.
---
=> feat: hide the nagging Upgrade button on Traefik's dashboard

renovate.json
Renovate shall not attempt further updates if a label named `renovate/stop_updating` is set.
---
=> feat: instruct Renovate per label to stop updating

renovate.json
Add descriptions to each Renovate package rule.
---
=> chore: add descriptions to each Renovate package rule

kestra/ansible/playbook-inline.yaml, kestra/ansible/playbook-password.yaml, kestra/ansible/playbook-ssh-key.yaml
Fix inconsistencies and style in Kestra Ansible examples.
---
=> Fix inconsistencies and style in Kestra Ansible examples

docker-compose/homepage/compose.yaml
Update `ghcr.io/tecnativa/docker-socket-proxy` docker tag to `0.3.0`.
=> chore(deps): update ghcr.io/tecnativa/docker-socket-proxy docker tag to 0.3.0

docker-compose/traefik/config/traefik.yaml
=> fix: update valid values of Traefik's log and accessLog setting

docker-compose/grafana/compose.yaml
Update docker.io/grafana/grafana-oss docker tag to v11.3.0
=> chore(deps): update docker.io/grafana/grafana-oss docker tag to v11.3.0

docker-compose/clamav/compose.yaml, docker-compose/clamav/config/clamd.conf, docker-compose/clamav/config/freshclam.conf, docker-compose/wazuh/.env.example, docker-compose/wazuh/compose.yaml, docker-compose/wazuh/config/postfix-relay/main.cf, docker-compose/wazuh/config/postfix-relay/sasl_passwd, docker-compose/wazuh/config/rules/local_rules.xml, docker-compose/wazuh/config/wazuh_cluster/wazuh_manager.conf, docker-compose/wazuh/config/wazuh_dashboard/opensearch_dashboards.yml, docker-compose/wazuh/config/wazuh_dashboard/wazuh.yml, docker-compose/wazuh/config/wazuh_indexer/internal_users.yml, docker-compose/wazuh/config/wazuh_indexer/wazuh.indexer.yml, docker-compose/wazuh/generate-certs.yaml
=> 517 add clamav compose and config

docker-compose/traefik/config/conf.d/tls.yaml.example
=> fix for tls example

kestra/ansible/playbook-inline.yaml, kestra/ansible/playbook-password.yaml, kestra/ansible/playbook-ssh-key.yaml, kestra/docker/file-build.yaml, kestra/docker/git-build.yaml, kestra/inputs.yaml, kestra/python/command.yaml, kestra/python/script.yaml, kestra/variables.yaml, kestra/webhook.yaml
Fixes done:
- Updated kestra plugins according to: https://kestra.io/docs/migration-guide/0.17.0/renamed-plugins
- Added more descriptive comments to all templates
=> update kestra templates

docker-compose/gitlab/compose.yaml, docker-compose/gitlab/config/gitlab.rb
Added new GitLab template that includes fixes:
- Added registry
- Traefik Labels and Templates
- Authentik Templates and config
=> initial gitlab deployment

docker-compose/gitea/.env.example, docker-compose/gitea/compose.yaml
https://github.com/ChristianLempa/boilerplates/issues/541
Added Gitea Compose Files
=> 541 Add Gitea Compose

docker-compose/wazuh/compose.yaml, docker-compose/wazuh/config/postfix-relay/main.cf, docker-compose/wazuh/config/postfix-relay/sasl_passwd
All items in #554 addressed. @cschug would you mind verifying if this is okay to merge? Thank you :)
=> fix for 554

docker-compose/gitea/compose.yaml, docker-compose/gitlab/compose.yaml, docker-compose/prometheus/config/prometheus.yaml, docker-compose/teleport/config/teleport.yaml, docker-compose/traefik/compose.yaml, docker-compose/traefik/config/conf.d/externalservice.yaml, docker-compose/traefik/config/conf.d/tls.yaml, docker-compose/traefik/config/traefik.yaml, docker-compose/wazuh/compose.yaml
Reduce number of errors and warnings reported by `yamllint` in Docker Compose files and configuration
=> Reduce number of errors and warnings reported by yamllint in Docker Compose files and configuration

docker-compose/mariadb/compose.yaml
Remove comment which applied before we were switching to using Renovate.
=> chore(deps): remove obsolete comment

.github/workflows/lint.yaml, .yamllint
Lint YAML files (file extensions `.yaml` & `.yml`) on pull requests on the `main` branch.
=> feat: lint YAML files on pull requests on the main branch

docker-compose/traefik/config/conf.d/externalservice.yaml
Hello. Thanks for the great boilerplate code. \
I noticed that some of your Traefik code could use some tweaks. Mainly the syntax for the list of `entryPoints` wasn't formatted quite right, and the example was missing a TLS provider. Something that took me way too long to realise ;) \
Hopefully these tweaks make it a bit easier to use.
---
=> Tweak boilerplate in Traefik's `externalservice.yaml`

docker-compose/traefik/config/example.externalservice.yaml
=> fix trailing whitespace

docker-compose/gitea/.env.example, packer/proxmox/ubuntu-server-focal-docker/ubuntu-server-focal-docker.pkr.hcl, packer/proxmox/ubuntu-server-focal/ubuntu-server-focal.pkr.hcl, packer/proxmox/ubuntu-server-jammy-docker/ubuntu-server-jammy-docker.pkr.hcl, packer/proxmox/ubuntu-server-jammy/ubuntu-server-jammy.pkr.hcl, packer/proxmox/ubuntu-server-noble/ubuntu-server-noble.pkr.hcl, terraform/civo/query.tf, terraform/helm/certmanager.tf, terraform/helm/traefik.tf, terraform/kubernetes/provider.tf, terraform/kubernetes/secret.tf, terraform/proxmox/full-clone.tf, terraform/templates/kubernetes-automation-example/certmanager.tf, terraform/templates/kubernetes-automation-example/nginx1.tf, terraform/templates/kubernetes-automation-example/provider.tf, terraform/templates/kubernetes-automation-example/traefik.tf
Cleanup trailing whitespace, no code change.
=> style: cleanup trailing whitespace

docker-compose/gitlab-runner/config/config.toml
=> gitlab runner config improvements

renovate.json
=> fix: remove spurious curly brace

packer/proxmox/ubuntu-server-noble/ubuntu-server-noble.pkr.hcl
Change iso_url and iso_checksum to newer version 24.04.2 since 24.04 isn't downloadable anymore
=> Change iso_url and iso_checksum to newer version 24.04.2

actions/gitlab/ansible/run.yml, actions/gitlab/ansible/test.yml, actions/gitlab/docker/config.yml, actions/gitlab/docker/deploy.yml, actions/gitlab/docker/test.yml, actions/gitlab/terraform/apply.yml, actions/gitlab/terraform/validate.yml
=> add gitlab component templates
