ChristianLempa/boilerplates

- docker-compose/nginxproxymanager/docker-compose.yaml
Changed MySQL hostname in the nignxproxymanager image from "db"(default setting from the official example) to match the name of the MariaDB container
> Fixed DB names not matching in the containers

- docker-compose/prometheus/exporters/cadvisor/docker-compose.yml
**Checklist:**
**Description:**
Since they don't update the latest tag... the latest tag is now 20 months old and it seems like they will/can not update it in the future...
Unsure what to do about that but for now I would just update the tag... ^^'
> Update cadvisor to `latest` version - not using the latest tag

- ansible/provisoning/ubuntu/install-docker.yaml
From [lookup plugin documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html#synopsis)
> Allows you to query the environment variables available on the controller when you invoked Ansible.
I assume the intended user here is the one in the VM (`vagrant` from your video) which can be accessed through `ansible_env` fact.
**EDIT:**
Added a `reset_connection` step after adding user to docker group, as per [docker post installation steps](https://docs.docker.com/engine/install/linux-postinstall/#:~:text=If%20testing%20on%20a%20virtual%20machine%2C%20it%20may%20be%20necessary%20to%20restart%20the%20virtual%20machine%20for%20changes%20to%20take%20effect.) this will allow change to take effect and prevent permission errors from hapenning later.
P.S. thanks …
> Use ansible_env fact instead of lookup plugin as the latter queries controller instead of remote

- docker-compose/prometheus/exporters/cadvisor/docker-compose.yml
Hi,
Cadvisor needs host networking or it can only see the network interfaces in the Cadvisor container itself, not all the interfaces of the docker server
> Cadvisor needs host networking

- ansible/configuration/fail2ban/config-f2b-protect-sshd.yaml
- ansible/configuration/ssh/config-add-sshkey.yaml
- ansible/deployment/portainer/deploy-portainer.yaml
- ansible/deployment/traefik/deploy-traefik.yaml
- ansible/installation/inst-core.yaml
- ansible/installation/inst-docker-ubuntu.yaml
- ansible/installation/inst-microk8s.yaml
- ansible/installation/inst-vm-core.yaml
- ansible/installation/inst-wireguard.yaml
- ansible/installation/inst-zsh.yaml
- ansible/maintenance/maint-diskspace.yaml
- ansible/maintenance/maint-docker-clean.yaml
- ansible/maintenance/maint-reboot-required.yaml
- ansible/maintenance/maint-reboot.yaml
- ansible/notification/notify-discord.yaml
Ensure that the `hosts` definition is always defined, defaulting to an empty set. Due to the lack of an Ansible inventory file this is most likely meant to be set as an Ansible extra variable [1].
We also rename the variable named `hosts` to `my_hosts` because `hosts` is a reserved name in Ansible. Reserved names in Ansible are for example all class variable names of plays, roles, blocks, and tasks [2], and
`hosts` for example is used by plays [3].
[1] https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#defining-variables-at-runtime
[2] https://github.com/ansible/ansible/blob/v2.16.4/lib/ansible/vars/reserved.py#L39
[3] https://github.com/ansible/ansible/blob/v2.16.4/lib/ansible/playbook/play.py#L58
Checklist:
> fix: ensure `hosts` is always defined

- docker-compose/nginx/docker-compose.yaml
Latest version of Nginx is 1.26.0.
---
> chore(deps): update docker.io/library/nginx docker tag to 1.26.0-alpine

- renovate.json
Clean up `renovate.json` a bit by fixing indentation and remove deprecations. Also add exceptions for Docker/Docker Compose-based MariaDB and MySQL version tracking in order to ignore major and minor version bumps (i.e., track patchlevel only) as it might break compatibility with applications using them.
---
> Rework renovate

- docker-compose/mariadb/docker-compose.yaml
Deliberately we do not set the most recent release version here in order to test the Renovate changes done in #247.
---
> chore(deps): do not use the `latest` tag for mariadb

- renovate.json
Do not apply the restrictions regarding major and minor version bumps to the standalone MariaDB Docker Compose which does not have to respect compatibility to a specific application.
---
> fix: fully upgrade standalone MariaDB Docker Compose by Renovate

- docker-compose/heimdall/docker-compose.yaml
- renovate.json
Alas over time the versioning schema of image tags by `lscr.io/linuxserver/heimdall` changed several times, ranging from simply incrementing a counter to a ISO 8601 date-alike variant to finally something which comes close the semantic versioning.
With the default rule set, Renovate gets fooled by the ISO 8601 date variant which was used in year 2021. The idea is to use a regular expression for better matching which kicks out 2021 using a negative lookahead and also require a minor version number in order not to get caught by the counter-like increments.
As a test, the image tag is intentionally set to `2.6.0` while `2.6.1` would be the latest release. This is just to verify whether Renovate does to right thing now.
---
> fix: attempt to fix Heimdall version tracking by Renovate

- renovate.json
> fix: avoid using negative lookaheads which Renovate doesn't understand

- renovate.json
Only bump the major version of PostgreSQL when using the standalone Docker Compose variant of PostgreSQL.
---
> fix: improve Renovate version tracking of PostgreSQL

- renovate.json
For Nginx container images, track stable releases only (i.e., the minor number is even).
---
> fix: track Nginx stable releases only

- renovate.json
Forgot to double-escape a backslash in `renovate.json`.
---
> fix: fix missing double-escaping of backslash

- renovate.json
It looks like Semaphore was tagged with an erroneous container image tag which should have rather read `v2.10.10` instead of `v2.19.10`. As this messes up version tracking and makes Renovate miss younger releases we ignore `v2.19.10`.
---
> chore(deps): ignore docker.io/semaphoreui/semaphore docker tag v2.19.10

- renovate.json
Adjust Renovate ignore rule regarding Semaphore `2.19.10`. 
Relates to #338.
---
> fix: adjust Renovate ignore rule regarding Semaphore 2.19.10

- ansible/deployment/portainer/deploy-portainer.yaml
- ansible/deployment/traefik/deploy-traefik.yaml
- ansible/maintenance/maint-reboot-required.yaml
- docker-compose/authentik/docker-compose.yaml
- docker-compose/cadvisor/docker-compose.yaml
- docker-compose/factory/runner-pool/docker-compose.yaml
- docker-compose/homepage/docker-compose.yaml
- docker-compose/portainer-agent/docker-compose.yaml
- docker-compose/portainer/docker-compose.yaml
- docker-compose/traefik/docker-compose.yaml
The use of `/var/run` was deprecated by FHS 3.0 nine years ago, so it's time to finally get rid of it where possible. The canonical directory for run-time variable data is `/run` nowadaya,s with `/var/run` just being a symbolic link for backward compatibilty and to ease transition.
---
> Replace `/var/run` by `/run`

- docker-compose/nextcloud/compose.yaml
* chore(deps): update docker.io/library/nextcloud docker tag to v30
* chore(deps): align recommended version of MariaDB to match Nextcloud 30
> chore(deps): update docker.io/library/nextcloud docker tag to v30 (#96)

- docker-compose/teleport/compose.yaml
Update public.ecr.aws/gravitational/teleport-distroless docker tag to v16.4.6
> chore(deps): update public.ecr.aws/gravitational/teleport-distroless docker tag to v16.4.6

- docker-compose/clamav/compose.yaml
- docker-compose/dockge/compose.yaml
- docker-compose/wazuh/compose.yaml
Use fully qualified container image name including the registry.
> fix: use fully qualified container image name including the registry

- ansible/docker/inst-docker-ubuntu.yaml
Don't try to install the obsolete `docker-scan-plugin` package and avoid being overly explicit by requesting transitive dependencies which get installed implicitly anyway.
Fixes #578.
> fix: adjust list of Docker packages to be installed

- .editorconfig
In order to support a more consistent formatting, this change adds a [EditorConfig](https://editorconfig.org/) configuration file `.editorconfig`.
> feat: add EditorConfig configuration

- renovate.json
Right now Renovate is stuck on `docker.io/ubuntu/bind9:9.18-23.10_edge` and does not detect tag `9.20-24.10_edge` as an update because it tries to stick with `23.10_edge` which gets interpreted as a compatibility hint which doesn't help here at all.
> fix: don't let Renovate get stuck on a misleading compatibility hint

- docker-compose/homepage/compose.yaml
As of hompage version 1.0 releases, it is required to set the `HOMEPAGE_ALLOWED_HOSTS` variable [1].
[1] https://gethomepage.dev/installation/#homepage_allowed_hosts
> chore(deps): update ghcr.io/gethomepage/homepage docker tag to v1

- docker-compose/nextcloud/compose.yaml
During the last major version bump, this reference was forgotten.
> chore(deps): fix Nextcloud version matrix reference

- docker-compose/loki/compose.yaml
Use fully qualified container image name for Loki.
> chore(deps): use fully qualified container image name for Loki

- docker-compose/gitlab/compose.yaml
Use fully qualified container image name for Gitlab CE.
> chore(deps): use fully qualified container image name for Gitlab CE

- docker-compose/gitlab-runner/compose.yaml
Use fully qualified container image name for Gitlab Runner.
While doing so, also switch to a versioned release of Gitlab Runner.
> chore(deps): use fully qualified container image name for Gitlab Runner

- docker-compose/gitea/compose.yaml
- Upgrade Gitea to `1.24.0`
- Upgrade PostgreSQL to `17.5`
- Use fully-qualified container image names
> chore(deps): update gitea docker tag to v1.24.0
